SOURCES = utils.ml context.ml syntax.ml lambda.ml translate.ml unification.ml hindleyMilner.ml logic.ml constraints.ml refinement.ml infer.ml main.ml
RESULT  = main
PACKS   = core
OCAMLFLAGS = -thread -custom
OCAMLLDFLAGS = -thread -custom -cclib -lstdc++

-include OCamlMakefile
