SOURCES = utils.ml syntax.ml lambda.ml translate.ml unification.ml hindleyMilner.ml logic.ml refinement.ml main.ml
RESULT  = main
PACKS   = core
OCAMLFLAGS = -thread -custom
OCAMLLDFLAGS = -thread -custom -cclib -lstdc++

-include OCamlMakefile
