SOURCES = utils.ml context.ml syntax.ml lambda.ml translate.ml unification.ml hindleyMilner.ml logic.ml constraints.ml refinement.ml infer.ml main.ml
RESULT  = main
PACKS   = core re2
THREADS = yes

-include OCamlMakefile
