name: GitHub Pages CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '15'
        check-latest: true
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Build
      run: |
        npm install
        VERSION=`git rev-parse --short HEAD` npm run build
      working-directory: ./wasm/site
    - name: Build documents
      run: |
        cargo doc --no-deps
        cp -r target/doc ${{ github.workspace }}/wasm/site/dist
      working-directory: ./impl-rust
    - name: Push gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ github.workspace }}/wasm/site/dist
